openapi: 3.0.1
info:
  title: parking-service
  version: 1.0.0
  description: |
    Parking Service

paths:
  /parking:
    get:
      tags:
        - parking-service
      summary: get available parking details
      responses:
        503:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        200:
          description: Posted data succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceDataResponse'
        404:
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
        400:
          description: Input data is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      security:
        - Bearer: []

#-----
components:
  schemas:
    ServiceDataResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ServiceCategoryResponse'
        pagging:
          $ref: '#/components/schemas/PagingInformation'
        status:
          $ref: '#/components/schemas/ResponseStatus'
    PagingInformation:
      type: object
      properties:
        totalRecords:
          type: number
        pageSize:
          type: integer
        pageNumber:
          type: integer
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ResponseStatus'
    ResponseStatus:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ServiceCategoryNotification:
      type: object
      properties:
        entityId:
          type: string
        email:
          type: string
        phone:
          type: string
        name:
          type: string
        message:
          type: string
        type:
          type: string
        appId:
          type: string
    ServiceCategoryResponse:
      type: object
      properties:
        id:
          type: string
        status:
          title: string
        subject:
          title: string
        description:
          title: string
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer